### ISSUE TITLE
Npm registry

### ISSUE THREAD

**Issue by SloRunner** [polilluminato/eobot-api#1]
is there an option to post this package to npm registry?

**Comment by polilluminato** [comment]
> is there an option to post this package to npm registry?

Yep, as soon as possible I'll create it. 
Meantime I have to learn how to do it ;-)

**Comment by SloRunner** [comment]
i can push it for you...

just git clone the repo, go in folder

npm login (create account before)
npm upload (i think)

**Comment by polilluminato** [comment]
I create an npm registry, go and grab it!

https://www.npmjs.com/package/eobot-api

**Comment by SloRunner** [comment]
nice thanks :) it will be easier for everyone now ;)
